FROM node:alpine
MAINTAINER paboulos
RUN apk update
RUN apk add inotify-tools
EXPOSE 3000
WORKDIR /app
ENV NODE_ENV=development

# add package.json and run npm install before adding the rest of the files
# this way, you only run npm install when package.json changes
ADD package.json /app
RUN yarn install
RUN yarn run build

